/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2020-08-06 13:45:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Dsbaihdtuvung_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/JAVA%20SERVLERT%20TOEIC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webhoctoeic/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1596709682220L));
    _jspx_dependants.put("jar:file:/D:/JAVA%20SERVLERT%20TOEIC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webhoctoeic/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hiển thị danh sách quản lí từ vựng</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"Static &amp; Dynamic Tables\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap & fontawesome -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"Template/Backend/assets/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"Template/Backend/assets/font-awesome/4.2.0/css/font-awesome.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- page specific plugin styles -->\r\n");
      out.write("\r\n");
      out.write("<!-- text fonts -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"Template/Backend/assets/fonts/fonts.googleapis.com.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- ace styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Template/Backend/assets/css/ace.min.css\"\r\n");
      out.write("\tclass=\"ace-main-stylesheet\" id=\"main-ace-style\" />\r\n");
      out.write("\r\n");
      out.write("<!-- inline styles related to this page -->\r\n");
      out.write("\r\n");
      out.write("<!-- ace settings handler -->\r\n");
      out.write("<script src=\"Template/Backend/assets/js/ace-extra.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"no-skin\">\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderAdmin.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"main-container ace-save-state\" id=\"main-container\">\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tace.settings.loadState('main-container')\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Begin menu -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- End menu -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Begin Content -->\r\n");
      out.write("\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t<div class=\"main-content-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"breadcrumbs ace-save-state\" id=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"ace-icon fa fa-home home-icon\"></i> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"Adminforward\">Trang chủ</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Quản lý phần hướng dẫn từ vựng</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\">Thêm danh sách bài hướng dẫn từ vựng</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!-- /.breadcrumb -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"page-content\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table id=\"simple-table\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"table  table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">Tên chủ đề từ vựng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">Hình chủ đề</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">Xóa</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">Thêm nội dung</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"center\">Checked nội dung</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Pagination-->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.Pagination-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-white btn-warning btn-bold\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-target=\"#myModal\">Thêm chủ đề từ vựng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"Themaudiohinhanhtuvung\" role=\"button\" class=\"btn btn-white btn-warning btn-bold\">Thêm audio và hình ảnh cho chủ đề từ vựng</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.main-content -->\r\n");
      out.write("\t\t<!-- End Content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Begin footer -->\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FooterAdmin.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- end footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"#\" id=\"btn-scroll-up\"\r\n");
      out.write("\t\t\tclass=\"btn-scroll-up btn btn-sm btn-inverse\"> <i\r\n");
      out.write("\t\t\tclass=\"ace-icon fa fa-angle-double-up icon-only bigger-110\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.main-container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"Themchudetuvung\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">Thêm chủ đề từ vựng</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- PAGE CONTENT BEGINS -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-3 control-label no-padding-right\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor=\"form-field-1\">Nhập tên</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"form-field-1-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Tên bài hướng dẫn ngữ pháp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"vocabularyname\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-info\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-check bigger-110\"></i> Thêm chủ đề từ vựng\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- basic scripts -->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if !IE]> -->\r\n");
      out.write("\t<script src=\"Template/Backend/assets/js/jquery.2.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if IE]>\r\n");
      out.write("<script src=\"Template/Backend/assets/js/jquery.1.11.1.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if !IE]> -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.jQuery\r\n");
      out.write("\t\t\t\t|| document\r\n");
      out.write("\t\t\t\t\t\t.write(\"<script src='Template/Backend/assets/js/jquery.min.js'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<\"+\"/script>\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if IE]>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" window.jQuery || document.write(\"<script src='Template/Backend/assets/js/jquery1x.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("</script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tif ('ontouchstart' in document.documentElement)\r\n");
      out.write("\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t.write(\"<script src='Template/Backend/assets/js/jquery.mobile.custom.min.js'>\"\r\n");
      out.write("\t\t\t\t\t\t\t+ \"<\"+\"/script>\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"Template/Backend/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- page specific plugin scripts -->\r\n");
      out.write("\t<script src=\"Template/Backend/assets/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"Template/Backend/assets/js/jquery.dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"Template/Backend/assets/js/dataTables.tableTools.min.js\"></script>\r\n");
      out.write("\t<script src=\"Template/Backend/assets/js/dataTables.colVis.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ace scripts -->\r\n");
      out.write("\t<script src=\"Template/Backend/assets/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t<script src=\"Template/Backend/assets/js/ace.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- inline scripts related to this page -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t//initiate dataTables plugin\r\n");
      out.write("\t\t\tvar oTable1 = $('#dynamic-table')\r\n");
      out.write("\t\t\t//.wrap(\"<div class='dataTables_borderWrap' />\")   //if you are applying horizontal scrolling (sScrollX)\r\n");
      out.write("\t\t\t.dataTable({\r\n");
      out.write("\t\t\t\tbAutoWidth : false,\r\n");
      out.write("\t\t\t\t\"aoColumns\" : [ {\r\n");
      out.write("\t\t\t\t\t\"bSortable\" : false\r\n");
      out.write("\t\t\t\t}, null, null, null, null, null, {\r\n");
      out.write("\t\t\t\t\t\"bSortable\" : false\r\n");
      out.write("\t\t\t\t} ],\r\n");
      out.write("\t\t\t\t\"aaSorting\" : [],\r\n");
      out.write("\r\n");
      out.write("\t\t\t//,\r\n");
      out.write("\t\t\t//\"sScrollY\": \"200px\",\r\n");
      out.write("\t\t\t//\"bPaginate\": false,\r\n");
      out.write("\r\n");
      out.write("\t\t\t//\"sScrollX\": \"100%\",\r\n");
      out.write("\t\t\t//\"sScrollXInner\": \"120%\",\r\n");
      out.write("\t\t\t//\"bScrollCollapse\": true,\r\n");
      out.write("\t\t\t//Note: if you are applying horizontal scrolling (sScrollX) on a \".table-bordered\"\r\n");
      out.write("\t\t\t//you may want to wrap the table inside a \"div.dataTables_borderWrap\" element\r\n");
      out.write("\r\n");
      out.write("\t\t\t//\"iDisplayLength\": 50\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//oTable1.fnAdjustColumnSizing();\r\n");
      out.write("\r\n");
      out.write("\t\t\t//TableTools settings\r\n");
      out.write("\t\t\tTableTools.classes.container = \"btn-group btn-overlap\";\r\n");
      out.write("\t\t\tTableTools.classes.print = {\r\n");
      out.write("\t\t\t\t\"body\" : \"DTTT_Print\",\r\n");
      out.write("\t\t\t\t\"info\" : \"tableTools-alert gritter-item-wrapper gritter-info gritter-center white\",\r\n");
      out.write("\t\t\t\t\"message\" : \"tableTools-print-navbar\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t//initiate TableTools extension\r\n");
      out.write("\t\t\tvar tableTools_obj = new $.fn.dataTable.TableTools(\r\n");
      out.write("\t\t\t\t\toTable1,\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\"sSwfPath\" : \"assets/swf/copy_csv_xls_pdf.swf\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\"sRowSelector\" : \"td:not(:last-child)\",\r\n");
      out.write("\t\t\t\t\t\t\"sRowSelect\" : \"multi\",\r\n");
      out.write("\t\t\t\t\t\t\"fnRowSelected\" : function(row) {\r\n");
      out.write("\t\t\t\t\t\t\t//check checkbox when row is selected\r\n");
      out.write("\t\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(row).find('input[type=checkbox]').get(0).checked = true\r\n");
      out.write("\t\t\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\"fnRowDeselected\" : function(row) {\r\n");
      out.write("\t\t\t\t\t\t\t//uncheck checkbox\r\n");
      out.write("\t\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(row).find('input[type=checkbox]').get(0).checked = false\r\n");
      out.write("\t\t\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\"sSelectedClass\" : \"success\",\r\n");
      out.write("\t\t\t\t\t\t\"aButtons\" : [\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sExtends\" : \"copy\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sToolTip\" : \"Copy to clipboard\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sButtonClass\" : \"btn btn-white btn-primary btn-bold\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sButtonText\" : \"<i class='fa fa-copy bigger-110 pink'></i>\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"fnComplete\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tthis\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.fnInfo(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<h3 class=\"no-margin-top smaller\">Table copied</h3>\\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Copied '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ (oTable1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.fnSettings()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.fnRecordsTotal())\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ' row(s) to the clipboard.</p>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t1500);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sExtends\" : \"csv\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sToolTip\" : \"Export to CSV\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sButtonClass\" : \"btn btn-white btn-primary  btn-bold\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sButtonText\" : \"<i class='fa fa-file-excel-o bigger-110 green'></i>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sExtends\" : \"pdf\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sToolTip\" : \"Export to PDF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sButtonClass\" : \"btn btn-white btn-primary  btn-bold\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sButtonText\" : \"<i class='fa fa-file-pdf-o bigger-110 red'></i>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sExtends\" : \"print\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sToolTip\" : \"Print view\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sButtonClass\" : \"btn btn-white btn-primary  btn-bold\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sButtonText\" : \"<i class='fa fa-print bigger-110 grey'></i>\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sMessage\" : \"<div class='navbar navbar-default'><div class='navbar-header pull-left'><a class='navbar-brand' href='#'><small>Optional Navbar &amp; Text</small></a></div></div>\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"sInfo\" : \"<h3 class='no-margin-top'>Print view</h3>\\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <p>Please use your browser's print function to\\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  print this table.\\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <br />Press <b>escape</b> when finished.</p>\",\r\n");
      out.write("\t\t\t\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t//we put a container before our table and append TableTools element to it\r\n");
      out.write("\t\t\t$(tableTools_obj.fnContainer())\r\n");
      out.write("\t\t\t\t\t.appendTo($('.tableTools-container'));\r\n");
      out.write("\r\n");
      out.write("\t\t\t//also add tooltips to table tools buttons\r\n");
      out.write("\t\t\t//addding tooltips directly to \"A\" buttons results in buttons disappearing (weired! don't know why!)\r\n");
      out.write("\t\t\t//so we add tooltips to the \"DIV\" child after it becomes inserted\r\n");
      out.write("\t\t\t//flash objects inside table tools buttons are inserted with some delay (100ms) (for some reason)\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t$(tableTools_obj.fnContainer()).find('a.DTTT_button').each(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar div = $(this).find('> div');\r\n");
      out.write("\t\t\t\t\t\t\tif (div.length > 0)\r\n");
      out.write("\t\t\t\t\t\t\t\tdiv.tooltip({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontainer : 'body'\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).tooltip({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontainer : 'body'\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t}, 200);\r\n");
      out.write("\r\n");
      out.write("\t\t\t//ColVis extension\r\n");
      out.write("\t\t\tvar colvis = new $.fn.dataTable.ColVis(oTable1, {\r\n");
      out.write("\t\t\t\t\"buttonText\" : \"<i class='fa fa-search'></i>\",\r\n");
      out.write("\t\t\t\t\"aiExclude\" : [ 0, 6 ],\r\n");
      out.write("\t\t\t\t\"bShowAll\" : true,\r\n");
      out.write("\t\t\t\t//\"bRestore\": true,\r\n");
      out.write("\t\t\t\t\"sAlign\" : \"right\",\r\n");
      out.write("\t\t\t\t\"fnLabel\" : function(i, title, th) {\r\n");
      out.write("\t\t\t\t\treturn $(th).text();//remove icons, etc\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//style it\r\n");
      out.write("\t\t\t$(colvis.button()).addClass('btn-group').find('button').addClass(\r\n");
      out.write("\t\t\t\t\t'btn btn-white btn-info btn-bold')\r\n");
      out.write("\r\n");
      out.write("\t\t\t//and append it to our table tools btn-group, also add tooltip\r\n");
      out.write("\t\t\t$(colvis.button()).prependTo('.tableTools-container .btn-group')\r\n");
      out.write("\t\t\t\t\t.attr('title', 'Show/hide columns').tooltip({\r\n");
      out.write("\t\t\t\t\t\tcontainer : 'body'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//and make the list, buttons and checkboxed Ace-like\r\n");
      out.write("\t\t\t$(colvis.dom.collection)\r\n");
      out.write("\t\t\t\t\t.addClass(\r\n");
      out.write("\t\t\t\t\t\t\t'dropdown-menu dropdown-light dropdown-caret dropdown-caret-right')\r\n");
      out.write("\t\t\t\t\t.find('li').wrapInner('<a href=\"javascript:void(0)\" />') //'A' tag is required for better styling\r\n");
      out.write("\t\t\t\t\t.find('input[type=checkbox]').addClass('ace').next()\r\n");
      out.write("\t\t\t\t\t.addClass('lbl padding-8');\r\n");
      out.write("\r\n");
      out.write("\t\t\t/////////////////////////////////\r\n");
      out.write("\t\t\t//table checkboxes\r\n");
      out.write("\t\t\t$('th input[type=checkbox], td input[type=checkbox]').prop(\r\n");
      out.write("\t\t\t\t\t'checked', false);\r\n");
      out.write("\r\n");
      out.write("\t\t\t//select/deselect all rows according to table header checkbox\r\n");
      out.write("\t\t\t$('#dynamic-table > thead > tr > th input[type=checkbox]').eq(0)\r\n");
      out.write("\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t'click',\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar th_checked = this.checked;//checkbox inside \"TH\" table header\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).closest('table').find('tbody > tr')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.each(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar row = this;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (th_checked)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttableTools_obj.fnSelect(row);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttableTools_obj.fnDeselect(row);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//select/deselect a row when the checkbox is checked/unchecked\r\n");
      out.write("\t\t\t$('#dynamic-table').on(\r\n");
      out.write("\t\t\t\t\t'click',\r\n");
      out.write("\t\t\t\t\t'td input[type=checkbox]',\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar row = $(this).closest('tr').get(0);\r\n");
      out.write("\t\t\t\t\t\tif (!this.checked)\r\n");
      out.write("\t\t\t\t\t\t\ttableTools_obj.fnSelect(row);\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\ttableTools_obj.fnDeselect($(this).closest('tr')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.get(0));\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(document).on('click', '#dynamic-table .dropdown-toggle',\r\n");
      out.write("\t\t\t\t\tfunction(e) {\r\n");
      out.write("\t\t\t\t\t\te.stopImmediatePropagation();\r\n");
      out.write("\t\t\t\t\t\te.stopPropagation();\r\n");
      out.write("\t\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//And for the first simple table, which doesn't have TableTools or dataTables\r\n");
      out.write("\t\t\t//select/deselect all rows according to table header checkbox\r\n");
      out.write("\t\t\tvar active_class = 'active';\r\n");
      out.write("\t\t\t$('#simple-table > thead > tr > th input[type=checkbox]').eq(0).on(\r\n");
      out.write("\t\t\t\t\t'click',\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar th_checked = this.checked;//checkbox inside \"TH\" table header\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(this).closest('table').find('tbody > tr').each(\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar row = this;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (th_checked)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(row).addClass(active_class).find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'input[type=checkbox]').eq(0)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.prop('checked', true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(row).removeClass(active_class).find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'input[type=checkbox]').eq(0)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.prop('checked', false);\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//select/deselect a row when the checkbox is checked/unchecked\r\n");
      out.write("\t\t\t$('#simple-table').on('click', 'td input[type=checkbox]',\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar $row = $(this).closest('tr');\r\n");
      out.write("\t\t\t\t\t\tif (this.checked)\r\n");
      out.write("\t\t\t\t\t\t\t$row.addClass(active_class);\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$row.removeClass(active_class);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t/********************************/\r\n");
      out.write("\t\t\t//add tooltip for small view action buttons in dropdown menu\r\n");
      out.write("\t\t\t$('[data-rel=\"tooltip\"]').tooltip({\r\n");
      out.write("\t\t\t\tplacement : tooltip_placement\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//tooltip placement on right or left\r\n");
      out.write("\t\t\tfunction tooltip_placement(context, source) {\r\n");
      out.write("\t\t\t\tvar $source = $(source);\r\n");
      out.write("\t\t\t\tvar $parent = $source.closest('table')\r\n");
      out.write("\t\t\t\tvar off1 = $parent.offset();\r\n");
      out.write("\t\t\t\tvar w1 = $parent.width();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar off2 = $source.offset();\r\n");
      out.write("\t\t\t\t//var w2 = $source.width();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (parseInt(off2.left) < parseInt(off1.left)\r\n");
      out.write("\t\t\t\t\t\t+ parseInt(w1 / 2))\r\n");
      out.write("\t\t\t\t\treturn 'right';\r\n");
      out.write("\t\t\t\treturn 'left';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /View/Admin/Dsbaihdtuvung.jsp(75,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msglsVocab!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<h4 class=\"pink\">\r\n");
          out.write("\t\t\t\t\t\t\t<i\r\n");
          out.write("\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-hand-o-right icon-animated-hand-pointer blue\"></i>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<a class=\"green\" data-toggle=\"modal\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msglsVocab}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\t\t\t\t\t\t</h4>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"hr hr-18 dotted hr-double\"></div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /View/Admin/Dsbaihdtuvung.jsp(104,11) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lsVocab}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /View/Admin/Dsbaihdtuvung.jsp(104,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.vocabularyguidelineid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"green\" href=\"DetailVocabTitle?pageid=1&vocabularyguidelineid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.vocabularyguidelineid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.vocabularyname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"Imageaudiohdtuvung/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.vocabularyimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\tclass=\"media-object\" alt=''  width=\"64px\" height=\"40px\"/></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\"><a class=\"red\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"#\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash-o bigger-130\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a></td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\"><a class=\"green\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"Themndchudetuvung?vocabularyguidelineid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.vocabularyguidelineid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-pencil bigger-130\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /View/Admin/Dsbaihdtuvung.jsp(127,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.checknoidung == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"ace-icon fa fa-check-square-o\"></i></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /View/Admin/Dsbaihdtuvung.jsp(130,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.checknoidung == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"ace-icon fa fa-square-o\"></i></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /View/Admin/Dsbaihdtuvung.jsp(151,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"disabled\"><a href=\"#\">Prev</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li  class=\"active\"><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /View/Admin/Dsbaihdtuvung.jsp(154,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage == 1 && numberpage < maxpageid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Next</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /View/Admin/Dsbaihdtuvung.jsp(158,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage == 1 && numberpage == maxpageid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li  class=\"disabled\"><a class=\"disabled\" href=\"#\">Next</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /View/Admin/Dsbaihdtuvung.jsp(164,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage > 1 && numberpage == maxpageid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Prev</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li  class=\"active\"><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"disabled\"><a href=\"#\">Next</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /View/Admin/Dsbaihdtuvung.jsp(171,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage > 1 && numberpage < maxpageid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Prev</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a class=\"active\" href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"Hienthidsquanlytuvung?pageid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberpage+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Next</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }
}
