/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2020-08-06 10:55:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Admin Page</title>\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap & fontawesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Template/Backend/assets/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"Template/Backend/assets/font-awesome/4.2.0/css/font-awesome.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- page specific plugin styles -->\r\n");
      out.write("\r\n");
      out.write("<!-- text fonts -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Template/Backend/assets/fonts/fonts.googleapis.com.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- ace styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Template/Backend/assets/css/ace.min.css\"\r\n");
      out.write("\tclass=\"ace-main-stylesheet\" id=\"main-ace-style\" />\r\n");
      out.write("\r\n");
      out.write("<!-- ace settings handler -->\r\n");
      out.write("<script src=\"Template/Backend/assets/js/ace-extra.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"no-skin\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderAdmin.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- End Header -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"main-container ace-save-state\" id=\"main-container\">\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttry{ace.settings.loadState('main-container')}catch(e){}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Begin menu -->\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- End menu -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Begin Content -->\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<div class=\"main-content-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"breadcrumbs ace-save-state\" id=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-home home-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"Adminforward\">Trang chủ</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul><!-- /.breadcrumb -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"page-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<center class=\"paddingtop-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img width=\"500\" height=\"250\" alt=\"\" src=\"Template/Backend/assets/images/homeadmin.gif\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- /.main-content -->\r\n");
      out.write("\t\t\t<!-- End Content -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Begin footer -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FooterAdmin.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- end footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\" id=\"btn-scroll-up\" class=\"btn-scroll-up btn btn-sm btn-inverse\">\r\n");
      out.write("\t\t\t\t<i class=\"ace-icon fa fa-angle-double-up icon-only bigger-110\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div><!-- /.main-container -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- basic scripts -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if !IE]> -->\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/jquery.2.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if !IE]> -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\twindow.jQuery || document.write(\"<script src='Template/Backend/assets/js/jquery.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tif('ontouchstart' in document.documentElement) document.write(\"<script src='Template/Backend/assets/js/jquery.mobile.custom.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/jquery-ui.custom.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/jquery.flot.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/jquery.flot.pie.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/jquery.flot.resize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ace scripts -->\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"Template/Backend/assets/js/ace.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- inline scripts related to this page -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t\t$('.easy-pie-chart.percentage').each(function(){\r\n");
      out.write("\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\tvar barColor = $(this).data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');\r\n");
      out.write("\t\t\t\t\tvar trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';\r\n");
      out.write("\t\t\t\t\tvar size = parseInt($(this).data('size')) || 50;\r\n");
      out.write("\t\t\t\t\t$(this).easyPieChart({\r\n");
      out.write("\t\t\t\t\t\tbarColor: barColor,\r\n");
      out.write("\t\t\t\t\t\ttrackColor: trackColor,\r\n");
      out.write("\t\t\t\t\t\tscaleColor: false,\r\n");
      out.write("\t\t\t\t\t\tlineCap: 'butt',\r\n");
      out.write("\t\t\t\t\t\tlineWidth: parseInt(size/10),\r\n");
      out.write("\t\t\t\t\t\tanimate: /msie\\s*(8|7|6)/.test(navigator.userAgent.toLowerCase()) ? false : 1000,\r\n");
      out.write("\t\t\t\t\t\tsize: size\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('.sparkline').each(function(){\r\n");
      out.write("\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\tvar barColor = !$box.hasClass('infobox-dark') ? $box.css('color') : '#FFF';\r\n");
      out.write("\t\t\t\t\t$(this).sparkline('html',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttagValuesAttribute:'data-values',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype: 'bar',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbarColor: barColor ,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchartRangeMin:$(this).data('min') || 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  //flot chart resize plugin, somehow manipulates default browser resize event to optimize it!\r\n");
      out.write("\t\t\t  //but sometimes it brings up errors with normal resize event handlers\r\n");
      out.write("\t\t\t  $.resize.throttleWindow = false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  var placeholder = $('#piechart-placeholder').css({'width':'90%' , 'min-height':'150px'});\r\n");
      out.write("\t\t\t  var data = [\r\n");
      out.write("\t\t\t\t{ label: \"social networks\",  data: 38.7, color: \"#68BC31\"},\r\n");
      out.write("\t\t\t\t{ label: \"search engines\",  data: 24.5, color: \"#2091CF\"},\r\n");
      out.write("\t\t\t\t{ label: \"ad campaigns\",  data: 8.2, color: \"#AF4E96\"},\r\n");
      out.write("\t\t\t\t{ label: \"direct traffic\",  data: 18.6, color: \"#DA5430\"},\r\n");
      out.write("\t\t\t\t{ label: \"other\",  data: 10, color: \"#FEE074\"}\r\n");
      out.write("\t\t\t  ]\r\n");
      out.write("\t\t\t  function drawPieChart(placeholder, data, position) {\r\n");
      out.write("\t\t\t \t  $.plot(placeholder, data, {\r\n");
      out.write("\t\t\t\t\tseries: {\r\n");
      out.write("\t\t\t\t\t\tpie: {\r\n");
      out.write("\t\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\t\ttilt:0.8,\r\n");
      out.write("\t\t\t\t\t\t\thighlight: {\r\n");
      out.write("\t\t\t\t\t\t\t\topacity: 0.25\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstroke: {\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor: '#fff',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth: 2\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstartAngle: 2\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tlegend: {\r\n");
      out.write("\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\tposition: position || \"ne\", \r\n");
      out.write("\t\t\t\t\t\tlabelBoxBorderColor: null,\r\n");
      out.write("\t\t\t\t\t\tmargin:[-30,15]\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\tgrid: {\r\n");
      out.write("\t\t\t\t\t\thoverable: true,\r\n");
      out.write("\t\t\t\t\t\tclickable: true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t })\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t drawPieChart(placeholder, data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t /**\r\n");
      out.write("\t\t\t we saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically\r\n");
      out.write("\t\t\t so that's not needed actually.\r\n");
      out.write("\t\t\t */\r\n");
      out.write("\t\t\t placeholder.data('chart', data);\r\n");
      out.write("\t\t\t placeholder.data('draw', drawPieChart);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  //pie chart tooltip example\r\n");
      out.write("\t\t\t  var $tooltip = $(\"<div class='tooltip top in'><div class='tooltip-inner'></div></div>\").hide().appendTo('body');\r\n");
      out.write("\t\t\t  var previousPoint = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  placeholder.on('plothover', function (event, pos, item) {\r\n");
      out.write("\t\t\t\tif(item) {\r\n");
      out.write("\t\t\t\t\tif (previousPoint != item.seriesIndex) {\r\n");
      out.write("\t\t\t\t\t\tpreviousPoint = item.seriesIndex;\r\n");
      out.write("\t\t\t\t\t\tvar tip = item.series['label'] + \" : \" + item.series['percent']+'%';\r\n");
      out.write("\t\t\t\t\t\t$tooltip.show().children(0).text(tip);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$tooltip.css({top:pos.pageY + 10, left:pos.pageX + 10});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$tooltip.hide();\r\n");
      out.write("\t\t\t\t\tpreviousPoint = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t/////////////////////////////////////\r\n");
      out.write("\t\t\t\t$(document).one('ajaxloadstart.page', function(e) {\r\n");
      out.write("\t\t\t\t\t$tooltip.remove();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d1 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\t\td1.push([i, Math.sin(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d2 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\t\td2.push([i, Math.cos(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d3 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.2) {\r\n");
      out.write("\t\t\t\t\td3.push([i, Math.tan(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar sales_charts = $('#sales-charts').css({'width':'100%' , 'height':'220px'});\r\n");
      out.write("\t\t\t\t$.plot(\"#sales-charts\", [\r\n");
      out.write("\t\t\t\t\t{ label: \"Domains\", data: d1 },\r\n");
      out.write("\t\t\t\t\t{ label: \"Hosting\", data: d2 },\r\n");
      out.write("\t\t\t\t\t{ label: \"Services\", data: d3 }\r\n");
      out.write("\t\t\t\t], {\r\n");
      out.write("\t\t\t\t\thoverable: true,\r\n");
      out.write("\t\t\t\t\tshadowSize: 0,\r\n");
      out.write("\t\t\t\t\tseries: {\r\n");
      out.write("\t\t\t\t\t\tlines: { show: true },\r\n");
      out.write("\t\t\t\t\t\tpoints: { show: true }\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\txaxis: {\r\n");
      out.write("\t\t\t\t\t\ttickLength: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tyaxis: {\r\n");
      out.write("\t\t\t\t\t\tticks: 10,\r\n");
      out.write("\t\t\t\t\t\tmin: -2,\r\n");
      out.write("\t\t\t\t\t\tmax: 2,\r\n");
      out.write("\t\t\t\t\t\ttickDecimals: 3\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tgrid: {\r\n");
      out.write("\t\t\t\t\t\tbackgroundColor: { colors: [ \"#fff\", \"#fff\" ] },\r\n");
      out.write("\t\t\t\t\t\tborderWidth: 1,\r\n");
      out.write("\t\t\t\t\t\tborderColor:'#555'\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('#recent-box [data-rel=\"tooltip\"]').tooltip({placement: tooltip_placement});\r\n");
      out.write("\t\t\t\tfunction tooltip_placement(context, source) {\r\n");
      out.write("\t\t\t\t\tvar $source = $(source);\r\n");
      out.write("\t\t\t\t\tvar $parent = $source.closest('.tab-content')\r\n");
      out.write("\t\t\t\t\tvar off1 = $parent.offset();\r\n");
      out.write("\t\t\t\t\tvar w1 = $parent.width();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tvar off2 = $source.offset();\r\n");
      out.write("\t\t\t\t\t//var w2 = $source.width();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tif( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';\r\n");
      out.write("\t\t\t\t\treturn 'left';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('.dialogs,.comments').ace_scroll({\r\n");
      out.write("\t\t\t\t\tsize: 300\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//Android's default browser somehow is confused when tapping on label which will lead to dragging the task\r\n");
      out.write("\t\t\t\t//so disable dragging when clicking on label\r\n");
      out.write("\t\t\t\tvar agent = navigator.userAgent.toLowerCase();\r\n");
      out.write("\t\t\t\tif(\"ontouchstart\" in document && /applewebkit/.test(agent) && /android/.test(agent))\r\n");
      out.write("\t\t\t\t  $('#tasks').on('touchstart', function(e){\r\n");
      out.write("\t\t\t\t\tvar li = $(e.target).closest('#tasks li');\r\n");
      out.write("\t\t\t\t\tif(li.length == 0)return;\r\n");
      out.write("\t\t\t\t\tvar label = li.find('label.inline').get(0);\r\n");
      out.write("\t\t\t\t\tif(label == e.target || $.contains(label, e.target)) e.stopImmediatePropagation() ;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('#tasks').sortable({\r\n");
      out.write("\t\t\t\t\topacity:0.8,\r\n");
      out.write("\t\t\t\t\trevert:true,\r\n");
      out.write("\t\t\t\t\tforceHelperSize:true,\r\n");
      out.write("\t\t\t\t\tplaceholder: 'draggable-placeholder',\r\n");
      out.write("\t\t\t\t\tforcePlaceholderSize:true,\r\n");
      out.write("\t\t\t\t\ttolerance:'pointer',\r\n");
      out.write("\t\t\t\t\tstop: function( event, ui ) {\r\n");
      out.write("\t\t\t\t\t\t//just for Chrome!!!! so that dropdowns on items don't appear below other items after being moved\r\n");
      out.write("\t\t\t\t\t\t$(ui.item).css('z-index', 'auto');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t\t\t$('#tasks').disableSelection();\r\n");
      out.write("\t\t\t\t$('#tasks input:checkbox').removeAttr('checked').on('click', function(){\r\n");
      out.write("\t\t\t\t\tif(this.checked) $(this).closest('li').addClass('selected');\r\n");
      out.write("\t\t\t\t\telse $(this).closest('li').removeClass('selected');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t//show the dropdowns on top or bottom depending on window height and menu position\r\n");
      out.write("\t\t\t\t$('#task-tab .dropdown-hover').on('mouseenter', function(e) {\r\n");
      out.write("\t\t\t\t\tvar offset = $(this).offset();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tvar $w = $(window)\r\n");
      out.write("\t\t\t\t\tif (offset.top > $w.scrollTop() + $w.innerHeight() - 100) \r\n");
      out.write("\t\t\t\t\t\t$(this).addClass('dropup');\r\n");
      out.write("\t\t\t\t\telse $(this).removeClass('dropup');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
