/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2020-08-06 15:06:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/JAVA%20SERVLERT%20TOEIC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webhoctoeic/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1596709682220L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Home Page</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"Template/Frontend/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"Template/Frontend/css/bootstrap-responsive.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"Template/Frontend/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--Font-->\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- SCRIPT \r\n");
      out.write("    ============================================================-->\r\n");
      out.write("<!--     <script src=\"http://code.jquery.com/jquery.js\"></script> -->\r\n");
      out.write("<script src=\"Template/Frontend/js/jquery-1.js\"></script>\r\n");
      out.write("<script src=\"Template/Frontend/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#size {\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#size1 {\r\n");
      out.write("\tpadding-top: 280px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--HEADER ROW-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- /HEADER ROW -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- begin search -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"span6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"size\">\r\n");
      out.write("\t\t\t\t\t<form name=\"myform\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Tìm kiếm\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 500px\" name=\"grammarname\" onkeyup=\"Search()\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end search -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!--Carousel\r\n");
      out.write("  ==================================================-->\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Slide.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- /Carousel -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Feature \r\n");
      out.write("  ==============================================-->\r\n");
      out.write("\t\t<div class=\"row feature-box\">\r\n");
      out.write("\t\t\t<div class=\"span12 cnt-title\">\r\n");
      out.write("\t\t\t\t<h1>Chúng tôi cung cấp cho bạn các giao diện học và thi thân\r\n");
      out.write("\t\t\t\t\tthiện với người dùng</h1>\r\n");
      out.write("\t\t\t\t<span>(--Học thử, Làm bài tập, Thi thử--)</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"span4\">\r\n");
      out.write("\t\t\t\t<img src=\"Template/Frontend/Image/guideline.png\">\r\n");
      out.write("\t\t\t\t<h2>Hướng dẫn phần từ vựng, ngữ pháp</h2>\r\n");
      out.write("\t\t\t\t<p>Cung cấp các bài hướng dẫn sát với đề thi.</p>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">Chi tiết\r\n");
      out.write("\t\t\t\t\t\t\t\t&rarr;</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"span4\">\r\n");
      out.write("\t\t\t\t<img src=\"Template/Frontend/Image/exercises.png\">\r\n");
      out.write("\t\t\t\t<h2>Bài tập phần nghe, đọc</h2>\r\n");
      out.write("\t\t\t\t<p>Chúng tôi cung cấp các dạng bài tập có trong đề thi Toeic.</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal1\">Chi tiết&rarr;</a>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"span4\">\r\n");
      out.write("\t\t\t\t<img src=\"Template/Frontend/Image/thitoeic.png\">\r\n");
      out.write("\t\t\t\t<h2>Đề thi thử</h2>\r\n");
      out.write("\t\t\t\t<p>Chúng tôi cung cấp cho các bạn đề thi sát với thi thật.</p>\r\n");
      out.write("\t\t\t\t<a href=\"Hienthidsdethi?pageid=1\">Chi tiết &rarr;</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- /.Feature -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"hr-divider\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Row View -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t<img src=\"Template/Frontend/img/responsive.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t<img class=\"hidden-phone\" src=\"Template/Frontend/img/icon4.png\"\r\n");
      out.write("\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t<h1>Fully Responsive</h1>\r\n");
      out.write("\t\t\t\t<p>Pellentesque habitant morbi tristique senectus et netus et\r\n");
      out.write("\t\t\t\t\tmalesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat\r\n");
      out.write("\t\t\t\t\tvitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit\r\n");
      out.write("\t\t\t\t\tamet quam egestas semper. Aenean ultricies mi vitae est. Mauris\r\n");
      out.write("\t\t\t\t\tplacerat eleifend leo.</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\">Read More &rarr;</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.Row View -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--Footer\r\n");
      out.write("==========================-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!--/.Footer-->\r\n");
      out.write("\t\t<div class=\"span12\" style=\"z-index: -99999999\">\r\n");
      out.write("\t\t   <!-- start Modal làm bt -->\r\n");
      out.write("\t\t  <div class=\"modal fade\" id=\"myModal1\" role=\"dialog\" >\r\n");
      out.write("\t\t    <div class=\"modal-dialog\">\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t      <!-- Modal content-->\r\n");
      out.write("\t\t      <div class=\"modal-content\">\r\n");
      out.write("\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t          <h4 class=\"modal-title\">DANH SÁCH LOẠI BÀI TẬP</h4>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t         \t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t          \t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"pull-left\"><img src=\"Template/Frontend/Image/loaibtdoc.png\" class=\"media-object\" alt='' /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"Hienthidsbtphandoc?pageid=1\">Bài tập phần đọc</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4> \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"pull-left\"><img src=\"Template/Frontend/Image/loaibtnghe.png\" class=\"media-object\" alt='' /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"Hienthidsbtnghe?pageid=1\">Bài tập phần nghe</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4> \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Thoát</button>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <!-- end modal -->\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <!-- start Modal -->\r\n");
      out.write("\t\t  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t    <div class=\"modal-dialog\">\r\n");
      out.write("\t\t    \r\n");
      out.write("<!-- \t\t      Modal content -->\r\n");
      out.write("\t\t      <div class=\"modal-content\">\r\n");
      out.write("\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t          <h4 class=\"modal-title\">DANH SÁCH LOẠI BÀI HƯỚNG DẪN</h4>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"Template/Frontend/Image/vocabulary.jpg\" class=\"media-object\" alt='' width=\"64px\" height=\"64px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"Hienthidshdtuvung?pageid=1\">Học từ vựng</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4> \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t          \t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"Template/Frontend/Image/loaibtdoc.png\" class=\"media-object\" alt='' />\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"Dsbaihdnguphapforward?pageid=1\">Bài hướng dẫn phần ngữ pháp</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4> \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Thoát</button>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <!-- end modal -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
