/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2020-08-06 10:55:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Đăng Nhập</title>\r\n");
      out.write("<meta name=\"description\" content=\"User login page\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap & fontawesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Template/Backend/assets/css/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Template/Backend/font/font-awesome.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"Template/Backend/assets/font-awesome/4.2.0/css/font-awesome.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- text fonts -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ace styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Template/Backend/assets/css/ace.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"assets/css/ace-part2.min.css\" />\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Template/Backend/assets/css/ace-rtl.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("\t\t  <link rel=\"stylesheet\" href=\"assets/css/ace-ie.min.css\" />\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"assets/js/html5shiv.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/respond.min.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"login-layout\">\r\n");
      out.write("\t<div class=\"main-container\">\r\n");
      out.write("\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-10 col-sm-offset-1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"login-container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-leaf green\"></i> <span class=\"red\">Ace</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"white\" id=\"id-text2\">Application</span>\r\n");
      out.write("\t\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"blue\" id=\"id-company-text\">&copy; Company Name</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"space-6\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"position-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"login-box\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"login-box visible widget-box no-border\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"header blue lighter bigger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-coffee green\"></i> Please Enter Your\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tInformation\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"space-6\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p  style=\"color:red\">");
      out.print(request.getAttribute("msgregister")!=null?request.getAttribute("msgregister"):" ");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"LoginController\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"block clearfix\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"block input-icon input-icon-right\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"Username\" name=\"membername\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> <label class=\"block clearfix\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"block input-icon input-icon-right\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" name=\"memberpass\"/> <i class=\"ace-icon fa fa-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"inline\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace\" /> <span class=\"lbl\"> Remember Me</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"width-35 pull-right btn btn-sm btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-key\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bigger-110\">Login</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space-4\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-or-login center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"bigger-110\">Or Login Using</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"space-6\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-login center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-primary\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a> <a class=\"btn btn-info\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a> <a class=\"btn btn-danger\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-google-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- /.widget-main -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"toolbar clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"HomeForward\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"forgot-password-link\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-arrow-left\"></i> Trở về trang chủ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-target=\"#signup-box\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"user-signup-link\"> I want to register <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /.widget-body -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /.login-box -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"signup-box\" class=\"signup-box widget-box no-border\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"header green lighter bigger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-users blue\"></i> New User\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tRegistration\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"space-6\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form name=\"registerForm\" action=\"RegisterController\" method=\"POST\" onsubmit=\"return validation()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"block clearfix\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"block input-icon input-icon-right\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"Full Name\" name=\"name\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> <label class=\"block clearfix\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"block input-icon input-icon-right\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"Username\" name =\"membername\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> <label class=\"block clearfix\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"block input-icon input-icon-right\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" class=\"form-control\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" id=\"pwd\" name=\"memberpass\"/> <i class=\"ace-icon fa fa-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> <label class=\"block clearfix\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"block input-icon input-icon-right\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" class=\"form-control\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Repeat password\" id=\"confpass\"/> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-retweet\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> <label class=\"block\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace\" /> <span class=\"lbl\"> I accept the <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"#\">User Agreement</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space-24\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"reset\" class=\"width-30 pull-left btn btn-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-refresh\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bigger-110\">Reset</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button id=\"submitReg\" type=\"submit\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"width-65 pull-right btn btn-sm btn-success\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"bigger-110\">Register</span> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-arrow-right icon-on-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"toolbar center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-target=\"#login-box\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"back-to-login-link\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-arrow-left\"></i> Back to login\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- /.widget-body -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /.signup-box -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.position-relative -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-fixed-top align-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<br /> &nbsp; <a id=\"btn-login-dark\" href=\"#\">Dark</a> &nbsp; <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"blue\">/</span> &nbsp; <a id=\"btn-login-blur\" href=\"#\">Blur</a>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp; <span class=\"blue\">/</span> &nbsp; <a id=\"btn-login-light\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">Light</a> &nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.col -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.row -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.main-content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.main-container -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- basic scripts -->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if !IE]> -->\r\n");
      out.write("\t<script src=\"Template/Backend/assets/js/jquery.2.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if IE]>\r\n");
      out.write("<script src=\"Template/Backend/assets/js/jquery.1.11.1.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if !IE]> -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.jQuery\r\n");
      out.write("\t\t\t\t|| document.write(\"<script src='Template/Backend/assets/js/jquery.min.js'>\"\r\n");
      out.write("\t\t\t\t\t\t+ \"<\"+\"/script>\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if IE]>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" window.jQuery || document.write(\"<script src='Template/Backend/assets/js/jquery1x.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("</script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tif ('ontouchstart' in document.documentElement)\r\n");
      out.write("\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t.write(\"<script src='Template/Backend/assets/js/jquery.mobile.custom.min.js'>\"\r\n");
      out.write("\t\t\t\t\t\t\t+ \"<\"+\"/script>\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- inline scripts related to this page -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction validation()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar name = document.registerForm.name.value;\r\n");
      out.write("\t\t\tvar membername = document.registerForm.membername.value;\r\n");
      out.write("\t\t\tif(name==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Please Enter Full Name\");\r\n");
      out.write("\t\t\t\tdocument.registerForm.name.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else if (membername =\"\") {\r\n");
      out.write("\t\t\t\talert(\"Please Enter UserName\");\r\n");
      out.write("\t\t\t\tdocument.registerForm.membername.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t$(document).on('click', '.toolbar a[data-target]', function(e) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tvar target = $(this).data('target');\r\n");
      out.write("\t\t\t\t$('.widget-box.visible').removeClass('visible');//hide others\r\n");
      out.write("\t\t\t\t$(target).addClass('visible');//show target\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//you don't need this, just used for changing background\r\n");
      out.write("\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t$('#btn-login-dark').on('click', function(e) {\r\n");
      out.write("\t\t\t\t$('body').attr('class', 'login-layout');\r\n");
      out.write("\t\t\t\t$('#id-text2').attr('class', 'white');\r\n");
      out.write("\t\t\t\t$('#id-company-text').attr('class', 'blue');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#btn-login-light').on('click', function(e) {\r\n");
      out.write("\t\t\t\t$('body').attr('class', 'login-layout light-login');\r\n");
      out.write("\t\t\t\t$('#id-text2').attr('class', 'grey');\r\n");
      out.write("\t\t\t\t$('#id-company-text').attr('class', 'blue');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#btn-login-blur').on('click', function(e) {\r\n");
      out.write("\t\t\t\t$('body').attr('class', 'login-layout blur-login');\r\n");
      out.write("\t\t\t\t$('#id-text2').attr('class', 'white');\r\n");
      out.write("\t\t\t\t$('#id-company-text').attr('class', 'light-blue');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t    $('#submitReg').click(function(event){\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t        data = $('#pwd').val();\r\n");
      out.write("\t\t\t        var len = data.length;\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t        if(len < 6) {\r\n");
      out.write("\t\t\t            alert(\"Password of length than 6 letter\");\r\n");
      out.write("\t\t\t            // Prevent form submission\r\n");
      out.write("\t\t\t            event.preventDefault();\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t         \r\n");
      out.write("\t\t\t        if($('#pwd').val() != $('#confpass').val()) {\r\n");
      out.write("\t\t\t            alert(\"Password and Confirm Password don't match\");\r\n");
      out.write("\t\t\t            // Prevent form submission\r\n");
      out.write("\t\t\t            event.preventDefault();\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t         \r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
